name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Printing Goodbye
        run: echo "Done - Bye!"
      - name: Printing Multi-line
        run: |
            echo "First Output"
            echo "Second Output"
            echo "Third Output"
